name: xpm
description: A sample command-line application.
version: 0.0.1
homepage: https://xpm.link

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  all_exit_codes: ^2.1.0
  args: ^2.3.1
  chunked_downloader: ^0.0.2
  console: ^4.1.0
  dio: ^4.0.6
  isar: ^3.0.5
  logger: ^1.1.0
  path: ^1.8.2
  process_run: ^0.12.3+2
  slug: ^1.0.1
