name: xpm
description: Universal package manager for any unix-like distro including macOS. Also experimental Windows support.
version: 0.0.31
homepage: https://xpm.link
repository: https://github.com/verseles/xpm
executables:
  xpm:

environment:
  sdk: '>=2.18.2 <3.1.0'

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
  yaml: ^3.1.1

dependencies:
  all_exit_codes: ^2.1.0
  args: ^2.3.1
  console: ^4.1.0
  crypto: ^3.0.2
  dio: ^4.0.6
  dloader: ^1.0.3
  executable: ^1.0.3
  interact: ^2.1.1
  isar: ^3.0.5
  path: ^1.8.2
  process_run: ^0.12.3+2
  slug: ^1.0.2
