name: xpm
description: A sample command-line application.
version: 0.0.1
homepage: https://xpm.link

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  process_run: ^0.12.3+2
