name: Releases

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:

  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        run: dart pub get
      - name: Format
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze
        run: dart analyze
      - name: Test
        run: dart test --exclude-tags=skip-ci

      - name: Compile on ${{ matrix.os }}
        if: runner.os != 'Windows'
        run: mkdir -p build && dart compile exe bin/xpm.dart -o build/xpm-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
      - name: Gzip compiled file on ${{ matrix.os }}
        if: runner.os != 'Windows'
        run: gzip --best --keep build/xpm-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)

      - name: Compile on Windows
        if: runner.os == 'Windows'
        run: mkdir -p build && dart compile exe bin/xpm.dart -o build/xpm-windows-${{ runner.arch }}
      - name: Gzip compiled file on Windows
        if: runner.os == 'Windows'
        run: gzip --best --keep build/xpm-windows-${{ env.PROCESSOR_ARCHITECTURE }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ !endsWith(github.ref, '.0') }}
          fail_on_unmatched_files: false
          append_body: true
          files: build/xpm-*
