name: Releases

on:
  push:
    tags:
      - "v0.1.[0-9]+*"

jobs:

  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        run: dart pub get
      - name: Format
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze
        run: dart analyze
      - name: Test
        run: dart test --exclude-tags=skip-ci
      - name: Compile on ${{ matrix.os }}
        if: matrix.os != 'windows-latest'
        run: mkdir -p build && dart compile exe bin/xpm.dart -o build/xpm
      - name: Compile on ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: mkdir -p build && dart compile exe bin/xpm.dart -o build/xpm.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          fail_on_unmatched_files: false
          append_body: true
          files: |
            xpm
            xpm.exe
